server:
    port: 8085
spring:
    profiles:
        active: local
    application:
        name: beer-brewery-db
    datasource:
        url: jdbc:postgresql://localhost:5433/beer_brewery
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                hbm2ddl:
                    auto: update
    flyway:
        enabled: true
        locations: classpath:db/migration/local
        baseline-on-migrate: true
        schemas: beer_brewery_schema
